In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
X_train = np.array([[1,1,1],[1,0,1],[1,0,0],[1,0,0],[1,1,1],[0,1,1],[0,0,0],[1,0,1],[0,1,0],[1,0,0]])
y_train = np.array([1,1,0,0,1,0,0,1,1,0])

In [7]:
print(X_train,y_train)
print(X_train.shape,y_train.shape)


[[1 1 1]
 [1 0 1]
 [1 0 0]
 [1 0 0]
 [1 1 1]
 [0 1 1]
 [0 0 0]
 [1 0 1]
 [0 1 0]
 [1 0 0]] [1 1 0 0 1 0 0 1 1 0]
(10, 3) (10,)


In [10]:
def compute_entropy(y):
    entropy = 0
    if len(y)==0:
        return 0
    p1 = len(y[y==1])/len(y)
    if p1!=0 and p1!= 1:
        entropy = -p1*np.log2(p1) - (1-p1)*np.log2(1-p1)
    return entropy
    

In [12]:
print("Entropy at root node: ", compute_entropy(y_train)) 


Entropy at root node:  1.0


In [15]:
def split_dataset(x, indices, features):
    left = []
    right = []
    for i in indices:
        if x[i][feature]==1:
            left.append(i)
        else:
            right.append(i)
    return left,right
    

In [19]:
root_indices = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

# Feel free to play around with these variables
# The dataset only has three features, so this value can be 0 (Brown Cap), 1 (Tapering Stalk Shape) or 2 (Solitary)
feature = 0

left_indices, right_indices = split_dataset(X_train, root_indices, feature)

print("Left indices: ", left_indices)
print("Right indices: ", right_indices)

Left indices:  [0, 1, 2, 3, 4, 7, 9]
Right indices:  [5, 6, 8]


In [22]:
def compute_information_gain(X, y, indices, feature):
    info = 0
    left, right = split_dataset(X_train, indices, feature)
    w_l = len(X[left])/len(X[indices])
    w_r = len(X[right])/len(X[indices])
    p_l = compute_entropy(y[left])
    p_r = compute_entropy(y[right])
    p_n = compute_entropy(y[indices])
    info = p_n - (w_l* p_l + w_r * p_r)
    return info
 
    

In [23]:
info_gain0 = compute_information_gain(X_train, y_train, root_indices, feature=0)
print("Information Gain from splitting the root on brown cap: ", info_gain0)
    
info_gain1 = compute_information_gain(X_train, y_train, root_indices, feature=1)
print("Information Gain from splitting the root on tapering stalk shape: ", info_gain1)

info_gain2 = compute_information_gain(X_train, y_train, root_indices, feature=2)
print("Information Gain from splitting the root on solitary: ", info_gain2)



Information Gain from splitting the root on brown cap:  0.034851554559677034
Information Gain from splitting the root on tapering stalk shape:  0.034851554559677034
Information Gain from splitting the root on solitary:  0.034851554559677034


In [28]:
def get_best_split(X, y, indices):
    n = X.shape[1]
    best_feature = -1
    max_gain = 0
    for feature in range(n):
        gain = compute_information_gain(X, y, indices, feature)
        if gain > max_gain: 
            max_gain = gain
            best_feature = feature
    return best_feature

In [29]:
best_feature = get_best_split(X_train, y_train, root_indices)
print("Best feature to split on: %d" % best_feature)

Best feature to split on: 0


Best feature to split on: 0
