In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [4]:
import matplotlib.pyplot as plt
%matplotlib widget
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import make_blobs
from IPython.display import display, Markdown, Latex
import logging
logging.getLogger("tensorflow").setLevel(logging.ERROR)
tf.autograph.set_verbosity(0)
from matplotlib.widgets import Slider

In [7]:
def softmax(z):
    ez = np.exp(z)
    sm = ez/np.sum(ez)
    return sm
plt.close("all")


In [8]:
centers = [[-5,2],[-2, -2], [1, 2], [5, -2]]
X_train, y_train = make_blobs(n_samples=2000, centers=centers, cluster_std=1.0,random_state=30)


In [11]:
#non-preferred
model = Sequential( 
    [
    Dense(25, activation='relu'),
    Dense(15, activation='relu'),
    Dense(4, activation='softmax')
    ]
)
model.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy(),
    optimizer =  tf.keras.optimizers.Adam(0.001),
)
model.fit(
        X_train,y_train,epochs=10
)

Epoch 1/10
63/63 [==============================] - 1s 2ms/step - loss: 1.1469
Epoch 2/10
63/63 [==============================] - 0s 2ms/step - loss: 0.4987
Epoch 3/10
63/63 [==============================] - 0s 2ms/step - loss: 0.2102
Epoch 4/10
63/63 [==============================] - 0s 2ms/step - loss: 0.1114
Epoch 5/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0759
Epoch 6/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0596
Epoch 7/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0499
Epoch 8/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0436
Epoch 9/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0395
Epoch 10/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0354


In [12]:
ans = model.predict(X_train)
print(ans[:2])
print("largest",np.max(ans),"smallest",np.min(ans))

63/63 [==============================] - 0s 1ms/step
[[1.8400240e-03 1.3488808e-02 9.7623652e-01 8.4346626e-03]
 [9.9402940e-01 5.7604834e-03 2.0359893e-04 6.4642668e-06]]
largest 0.9999941 smallest 5.3816933e-09


In [14]:
#preferred implimentation
model = Sequential(
    [
        Dense(25, activation='relu'),
        Dense(15, activation='relu'),
        Dense(4, activation='linear'),
        ]
)
model.compile(
    loss = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer = tf.keras.optimizers.Adam(0.001),
)
model.fit(
    X_train, y_train, epochs=10
)

Epoch 1/10
63/63 [==============================] - 1s 2ms/step - loss: 1.0429
Epoch 2/10
63/63 [==============================] - 0s 2ms/step - loss: 0.4282
Epoch 3/10
63/63 [==============================] - 0s 2ms/step - loss: 0.2399
Epoch 4/10
63/63 [==============================] - 0s 2ms/step - loss: 0.1463
Epoch 5/10
63/63 [==============================] - 0s 2ms/step - loss: 0.1013
Epoch 6/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0782
Epoch 7/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0647
Epoch 8/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0558
Epoch 9/10
63/63 [==============================] - 0s 1ms/step - loss: 0.0495
Epoch 10/10
63/63 [==============================] - 0s 2ms/step - loss: 0.0449


In [16]:
ans = model.predict(X_train)
print(f"two output vectors are {ans[:2]}")
print("Largest value",np.max(ans), "Smallest:", np.min(ans))

63/63 [==============================] - 0s 1ms/step
two output vectors are [[-2.1132557  -2.6105309   3.2444024  -0.12366141]
 [ 3.6441014  -0.69153523 -3.2662814  -6.228953  ]]
Largest value 13.281128 Smallest: -10.486323


In [18]:
#to get probability form
prob = tf.nn.softmax(ans).numpy()
print(f"two output vectors are {prob[:2]}")
print("Largest value",np.max(prob), "Smallest:", np.min(prob))

two output vectors are [[4.5218552e-03 2.7501280e-03 9.5966160e-01 3.3066373e-02]
 [9.8605466e-01 1.2910942e-02 9.8346733e-04 5.0826231e-05]]
Largest value 0.9999977 Smallest: 4.763494e-11


In [20]:
#to find most likely
for i in range(5):
    print(f"{ans[i]}, category:{np.argmax(ans[i])}")


[-2.1132557  -2.6105309   3.2444024  -0.12366141], category:2
[ 3.6441014  -0.69153523 -3.2662814  -6.228953  ], category:0
[ 2.5687032  -0.21506658 -2.556619   -5.017484  ], category:0
[-1.8757044  3.2435255 -1.7678591 -2.3877275], category:1
[-0.86554796 -4.2452507   4.804354   -2.1358387 ], category:2
